name: CI

on:
push:
  branches:
    - main
pull_request:
  branches:
    - main

jobs:
build-and-test:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "9.0.x"

    - name: Restore dependencies
      run: dotnet restore ExplorandoMarte.sln

    - name: Build
      run: dotnet build ExplorandoMarte.sln --no-restore

    - name: Run Tests
      run: dotnet test ExplorandoMarte.sln --no-build --verbosity normal
